### ISSUE TITLE
Przygotować timer

### ISSUE THREAD

**Issue by dar-puch** [girlsjs/zadanie-quiz#32]
UWAGA PORZĄDKOWA: Zanim przypiszesz się do zadania, upewnij się, że nie masz przypisanego żadnego innego. Dopiero po jego zakończeniu weź następne.

Opis zadania:

Timer pokazujący czas, który upłynął od początku testu. W formie np 00:21 albo dowolnej innej. Aktualizować się co 1 sekundę. Zatrzyma się w momencie zatwierdzenia ostatniego pytania. Umieścimy go w panelu informacyjnym gdy ten będzie gotowy.

**Comment by NataD** [comment]
Kilka uwag do timera:
1. Trzeba przenieść timer do panelu informacyjnego gdy ten będzie skończony 
4. W momencie gdy timer dojdzie do zera, trzeba zablokować button z id=“next-btn” (czy coś podobnego). Na razie dodałam info że 'Zakończył się czas'

**Comment by dar-puch** [comment]
Ha, zaskoczyło mnie, że timer odlicza czas wstecz. Myślałam, że będzie liczył od 0 do przodu i na koniec testu oprócz wyniku pokaże czas, w jakim rozwiązano test. Ale zostańmy przy Twoim rozwiązaniu, jest ciekawe. 

1. Tak, zgadza się
2. Tak, albo zakończyć quiz i pokazać ekran result.
