### ISSUE TITLE
Poprawić panel informacyjny wg wskazówek

### ISSUE THREAD

**Issue by dar-puch** [girlsjs/zadanie-quiz#49]
1.	w index.html Ponumeruj id stepów od 0. Będzie wtedy tak samo jak current question a to nam się przyda
	2.	 Funkcja next() może być dużo krótsza. Oto przepis:
	3.	Nie musimy tworzyć zmiennej step, ponieważ wystarczy nam informacja, jaki jest numer obecnego pytania. Mamy ją w zmiennej currentQuestion. A więc taki step, którego numer odpowiada bieżącemu pytaniu, powinien mieć klasę is-active. Największym problemem będzie selektor w document.getElementById. Wiemy, że ma mieć na początku słowo "step" i potem doklejoną liczbę równą currentQuestion. Jak to zapisać? Jest taki rodzaj stringa, który może przyjmować zmienne, nazywa się template literal. Wyrażenie piszemy w tylnych ciapkach (`o takich `) a zmienne w nim po dolarze i w wąsach, np ${zmienna}. czyli gdy np let zmienna = spacery to wyrażenie `lubię ${zmienna}` wyświetli się jako lubię spacery. W takim templete literal napiszmy więc selektor document.getElementById( `step${currentQuestion}` ) i przypiszmy mu klasę is-active 
	4.	Wtedy jednak klasę is-active będzie miał każdy step po kolei. Dlatego najpierw wyszukajmy wszystko co ma klasę is-active (tworząc zmienną "active")i zabierzmy mu ją. 
	5.	Teraz przy pierwszym pytaniu wyskoczy błąd, ponieważ nic nie ma klasy is-active a więc nasza zmienna active będzie miała wartość null . Żeby temu zapobiec, możemy napisać warunek, że jeśli gdy element active istnieje (czyli poprostu if (active)), to zabierz od niego klasę is-active. Krócej można to zapisać jako short circuit, który wygląda tak: active && (to zamiast if) i dalej reszta. 
	6.	Teraz zostało nam jeszcze przypisanie klasy is-complete. Musimy ją nadać poprzedniemu stepowi, który wcześniej był active. Pozostałe zaliczone elementy już ją mają bo z pytaniami idziemy po kolei i nie usuwamy klasy is-complete. W zmiennej complete zapiszmy element o id zaczynającym się od step i numerem o 1 mniejszym od currentQuestion. Następnie do complete dodajmy klasę is-complete. Zabezpieczmy się warunkiem complete && 
	7.	To jest koniec funkcji next. Możemy ją wywołać wewnątrz funkcji showNextQuestion

**Comment by NataD** [comment]
@dar-puch, gdzie można zobaczyć funkcję next()? Na gałęzi master raczej nie ma tego co jest wymagane w issue

**Comment by dar-puch** [comment]
@NataD zaraz zobaczę o co chodzi, to zadanie tak długo tu wisi, że mogło się coś pozmieniać. Btw, jesteś świetna. Dzięki Tobie wreszcie skończymy tę apkę :)

**Comment by dar-puch** [comment]
@NataD  odnalazłam ten kod i dołączam ponownie - nie był nigdy zmerge'owany dlatego zniknął. W zadaniu jest opisany taki podstawowy refaktor ale tak naprawdę trzeba by jeszcze więcej pozmieniać bo na razie panel może pokazywać tylko 4 pytania ...
