### ISSUE TITLE
wyśrodkować tekst timera

### ISSUE THREAD

**Issue by dar-puch** [girlsjs/zadanie-quiz#54]

**Comment by NataD** [comment]
@dar-puch, względem czego powinien być wyśrodkowany tekst timera?

**Comment by dar-puch** [comment]
@NataD wiesz co, chyba już to poprawiłaś w poprzednim zadaniu. Wcześniej był wyrównany do lewej

**Comment by NataD** [comment]
ok, to w takim razie nic tu nie robię
